### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Monstergerm**
I don't think this worked. I am not using Github enough to ever understand how it works.

### CODE REVIEW

**Comment by Colorado4Wheeler** [comment]
What are you trying to do?

**Comment by Monstergerm** [comment]
I just want to upload a few changes to this plugin. But I made changes to an earlier version, so I do not want to automatically merge those since my changes need to be slightly modified to make them compatible with the latest version.

**Comment by kmarkley** [comment]
Thanks for the contribution.  Unfortunately the pull request didn't really go right. It looks like you didn't fork the repo until after you made the changes.

I have some questions about your added features.

1. You said in a PM you needed to save/recall player position to change speakers.  Can you elaborate?  Especially, why is it not sufficient to just pause iTunes vs saving/recalling the player position?

2. Does it ever make sense to save the player position without pausing?  Seems like no.

3. Does it ever make sense to recall the player position without also recalling the track? Again, seems like no.

4. Given 2 & 3 above, would it make more sense to think of these actions as "Stop and save track/position" and "Resume saved track/position playback"?

5. What plays next **after** resuming a saved track and player position is highly dependent on what else has happened since saving it.  Is the idea to pick up at a particular place in a playlist, or something else? 

6. What is the use-case for saving track duration to a variable?

And a quick note:  Your change to saving airplay devices seems simpler, but it will break if an airplay device ever has a comma in it's name.  I think I need to leave that alone for the time being.

**Comment by Monstergerm** [comment]
Yes, I always have problem with this fork thing in Github. It is really hard to understand github unless you use it a lot.

All my uses for this come from that I send iTunes music via an Airplay device to Nuvo.
Nuvo is a wholehouse music distribution system with keypads in every room. If you use official Nuvo sources, like their iPod docks and Music Servers, those Nuvo keypads display all metadata information including track lengths and player position.

If I play music from iTunes the keypad stays blank. However, there is an Indigo Nuvo plugin available that can control Nuvo and iTunes via the keypads using  a serial interface. I modified the plugin to send iTunes metadata and track information to the keypad.

So, in other words, when ever someone changes a song or a track position in the iTunes app, or makes changes on the Nuvo keypad etc. I need to capture the current player position and track duration so it will be correctly displayed on the keypads.

Currently, I run a combination of applescripts and the official iTunes plugin to accomplish this. Your plugin allows me to get rid of the applescripts. Also your plugin captures playlists, a feature that got lost with the official iTunes plugin.

Specifically to your questions
1. I need track duration and player position to tell Nuvo what to show on the keypads
2. Player pos needs to be updated if someone keeps clicking on the track at different timepoints, while it is playing.
3. I have many other triggers to update track, album, artist etc whenever they change and then have those changes sent to Nuvo. I recall what ever I need through a combination of triggers and actions.
4. Yes and no, I definitively have those stop and resume triggers but I need track length and player pos outside stop/resume requests.
5. It does not really matter what happens after a resume. I have a trigger whenever iTunes starts playing again it sends current track info, album artist, track duration, player position to Nuvo so the keypads display the correct information
6. see 1. Also the variables are how I communicate information between your plugin and the Nuvo plugin

So, I find it very useful to have those things and since they do not break the plugin I thought others might find some uses for it. But not many people have wholehouse music systems, so I don’t mind if you rather not want to clutter up the plugin with more things.

And yes, commas will brake the airplay device variable. You could add a check to prohibit commas.


So another question, how does your plugin handle if the local iTunes app is not running? Can it still build the applescript? I am asking since I also want to develop a setup for controlling a remote iTunes on another network computer. It looks like on initial load of the plugin the remote iTunes needs to be open, while subsequently I can quit iTunes without causing harm to the plugin.

**Comment by kmarkley** [comment]
I gotta think about this.  Your use is _very_ specific.  The additions don't break the plugin, but they do open up some weirdnesses.  Recalling a player position is kind of pointless without also recalling the track it related too.  For most uses, saving a player position is obsolete as soon as it happens, and applescript is ill-suited to monitor/update playback progress continuously.

Since you are using this with a modified version of the Nuvo plugin, it might make sense to also keep using a modified version of this one.

If I can think of way to meet your needs that also provides value to general users, I may still reconsider.

**Comment by kmarkley** [comment]
Wow, just skimmed the diff and that's an impressive number of changes.  Thanks so much for doing this.  I'll push an update as soon as I've had a chance to test it.

**Comment by Monstergerm** [comment]
Yes, please review carefully. I also just noticed in Github  that we had a discussion a few years ago and some of your concerns from that time might still apply. However, the iTunes plugin is going to go away and we need your plugin to control and retrieve as much info (metadata) as possible from iTunes/Music. So I added a few more actions that are useful for the general public and a few actions that apply more to users of the Nuvo plugin (metadata support on Nuvo keypads) but should not confuse the general public. 
I did not test the fader extensively since I don’t use it. This code section had several Python 3 incompatibilities.

**Comment by Monstergerm** [comment]
Hi,

The version check for iTunes vs Music app needs to be modified. >=10 catches incorrectly Mojave and many lower MacOS that still use iTunes.

Mojave (10.14) was the last OS using iTunes
Catalina (10.15) uses Music app
Big Sur (11.6) and thereafter uses Music app

One possibility ...
Instead of import os, import platform

mac_base_ver = int(platform.mac_ver()[0].split(".")[0])
mac_minor_ver = int(platform.mac_ver()[0].split(".")[1])
if mac_base_ver > 10 or (mac_base_ver == 10 and mac_minor_ver >= 15):
	AS_TARGET_NAME = "Music"

**Comment by kmarkley** [comment]
Thanks for the catch.  I skipped several os versions so I was confused about version numbers.

I think there is a more concise way to do the same thing:
```
import platform
mac_ver = tuple([int(s) for s in platform.mac_ver()[0].split(".")])
if mac_ver >= (10,15,0):
    AS_TARGET_NAME = "Music"
else:
    AS_TARGET_NAME = "iTunes"
```
Not sure when I'll be able to update and release.

**Comment by Monstergerm** [comment]
Much more elegant. I wish I knew more about Python.

Thanks for creating this great plugin in the first place. I wish the Indigo people would update the iTunes Plugin for Python 3. I have to switch all my music and announcement stuff over to your plugin with a combination of Airfoil Pro.

Please update as soon as you can since the new version will break for users on Mojave and lower.

**Pull request merged**
